// Generates app/(site)/blog/_data/posts-meta.ts — a lightweight,
// listing-only projection of BLOG_POSTS (no `body`/`faq`) so client
// components that only render post cards (title/description/date/etc.)
// don't ship every post's full article content to the browser.
//
// Re-run this whenever app/(site)/blog/_data/posts.ts changes:
//   npx tsx scripts/generate-blog-meta.ts

import { writeFileSync } from 'fs';
import { BLOG_POSTS } from '../app/(site)/blog/_data/posts';

const META = BLOG_POSTS.map((post) => ({
  slug: post.slug,
  title: post.title,
  description: post.description,
  category: post.category,
  datePublished: post.datePublished,
  dateModified: post.dateModified,
  readingMinutes: post.readingMinutes,
}));

const header = `// AUTO-GENERATED by scripts/generate-blog-meta.ts — do not edit by hand.
// Re-run \`npx tsx scripts/generate-blog-meta.ts\` after changing posts.ts.
import type { BlogCategory } from './categories';

export interface BlogPostMeta {
  slug: string;
  title: string;
  description: string;
  category: BlogCategory;
  datePublished: string;
  dateModified?: string;
  readingMinutes: number;
}

export const BLOG_POSTS_META: BlogPostMeta[] = `;

const body = JSON.stringify(META, null, 2)
  // JSON.stringify drops undefined values already, matching the optional field.
  .replace(/"([a-zA-Z0-9_]+)":/g, '$1:');

const output = `${header}${body};\n`;

writeFileSync(new URL('../app/(site)/blog/_data/posts-meta.ts', import.meta.url), output);
console.log(`Wrote posts-meta.ts with ${META.length} posts.`);
